In [1]:
import tensorflow as tf

In [2]:
print(type(tf))
print(tf.__version__)

<class 'module'>
2.2.0


In [3]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)
print(c)

tf.Tensor(3, shape=(), dtype=int32)


In [9]:
d = tf.multiply(a,b)
e = tf.add(c,b)
f = tf.subtract(d,e)

In [12]:
#sess = tf.Session() # Older TF Versions 
sess = tf.compat.v1.Session()

In [13]:
#outs = sess.run(f)

RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

In [16]:
# Build a dataflow graph.
ac = tf.constant([[1.0, 2.0], [3.0, 4.0]])
ad = tf.constant([[1.0, 1.0], [0.0, 1.0]])
ae = tf.matmul(ac, ad)

print(ae)

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)


In [18]:
# Construct a `Session` to execute the graph.
with tf.compat.v1.Session() as sess:

  # Build a dataflow graph.
  sc = tf.constant([[1.0, 2.0], [3.0, 4.0]])
  sd = tf.constant([[1.0, 1.0], [0.0, 1.0]])
  se = tf.matmul(sc, sd)

  # Execute the graph and store the value that `e` represents in `result`.
  result = sess.run(se)
  print(result)
sess.close()

[[1. 3.]
 [3. 7.]]


In [24]:
tf_var_str = tf.Variable("Hi Rohit - Assign a String to this tf_var_str",tf.string)
print(type(tf_var_str)) ## <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
tf_var_int = tf.Variable(1234,tf.int32)
print(type(tf_var_int)) ## same class as var_str ## <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [25]:
tf.rank(tf_var_str) ## RANK == 0 --and thus its a SCALAR == numpy=0

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [31]:
tf_var_str1 = tf.Variable(["Hi Rohit"],tf.string)
tf.rank(tf_var_str1) ## RANK == 1 -as its got 1 Dimension -1 ARRAY - 1 LIST -- and thus NOT a SCALAR == numpy=1

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [32]:
tf_var_str1_a = tf.Variable(["Hi Rohit","Still-Rank-1"],tf.string)
tf.rank(tf_var_str1_a) ## RANK == 1 -as its got 1 Dimension -1 ARRAY - 1 LIST with 2 STR ELEMENTS -- and thus NOT a SCALAR == numpy=1

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [29]:
tf_var_str2 = tf.Variable([["Hi Rohit"], ["Assign a String to this tf_var_str"]],tf.string)
tf.rank(tf_var_str2) ## RANK == 2 -as its got 2 Dimensions-2 ARRAYS - 2 LISTS -- and thus NOT a SCALAR == numpy=2

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [8]:
from tensorflow import keras
print(type(keras))
fashion_mnist_data = keras.datasets.fashion_mnist
print(type(fashion_mnist_data))
(train_images,train_labels) , (test_images,test_labels) = fashion_mnist_data.load_data()

<class 'module'>
<class 'module'>
4423680/4422102 [==============================] - 0s 0us/step


In [9]:
print(train_images.shape)
print(train_labels.shape)

(60000, 28, 28)
(60000,)


In [20]:
with tf.compat.v1.Session() as sess:
    fetches = [a,b,c,d,e,f]
    outs = sess.run(fetches)

AttributeError: Tensor.graph is meaningless when eager execution is enabled.